spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false